addpath('stageA/');
addpath('stageB/');
addpath('experiment2/');
u = double(imread('Lenna.png'))/255;
img = u(200:256,190:246,3);
x = size(img, 1);
y = size(img, 2);
fullimagesize = x*y;
sigma=0.3;
ImagePatches = nlfilter(img, [5 5], @(block) {block});
X = cat(3, ImagePatches{:});
X = permute(X, [3, 1, 2]);
X = reshape(X, [fullimagesize, 5^2]);
cropsize = 5;
nbsparse = 7;
Wtild = WeightMatrix(img, sigma, cropsize);
W = SparseWeightMatrix(Wtild, nbsparse);
D = diag(sum(W,2));
A = sqrt(inv(D))*W*sqrt(inv(D));
disp('Computed W matrix');